name: CI

on: [push, pull_request]

env:
  NEXTAUTH_SECRET: "secret"
  NEXTAUTH_URL: "http://localhost:3000"
  GOOGLE_CLIENT_ID: "1234"
  GOOGLE_CLIENT_SECRET: "secret"
  DATABASE_URL: "https://example.com"
  TMDB_API_KEY: "secret"
  ADMINISTRATOR_EMAIL: "john.doe@gmail.com"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: "latest"
      - uses: actions/setup-node@v3
        with:
          node-version: "latest"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Format
        run: pnpm format

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Verify Working Environment Variables
        run: |
          echo "NEXTAUTH_SECRET: $NEXTAUTH_SECRET"
          echo "NEXTAUTH_URL: $NEXTAUTH_URL"
          echo "GOOGLE_CLIENT_ID: $GOOGLE_CLIENT_ID"
          echo "GOOGLE_CLIENT_SECRET: $GOOGLE_CLIENT_SECRET"
          echo "DATABASE_URL: $DATABASE_URL"
          echo "TMDB_API_KEY: $TMDB_API_KEY"
          echo "ADMINISTRATOR_EMAIL: $ADMINISTRATOR_EMAIL"
